"""These 'constants' are used to lookup the relevant locale string from language_strings.json"""
SKILL_NAME = "SKILL_NAME"
WELCOME = "WELCOME"
HELP = "HELP"
GOODBYE = "GOODBYE"
THERE_ARE = "THERE_ARE"
SLEEPS_UNTIL = "SLEEPS_UNTIL"
JENTRIS_IS_ON = "JENTRIS_IS_ON"
ERROR = "ERROR"
J_DAY = "J_DAY"
